### ISSUE TITLE
After the last update keep geting this error:

### ISSUE THREAD

**Issue by Ar4g0rn** [tntwist/binance-trade-bot#20]
Error while scouting...
Traceback (most recent call last):
  File "/BTB-Install-script/Binance1/binance-trade-bot/binance_trade_bot/scheduler.py", line 25, in _run_job
    super()._run_job(job)
  File "/usr/local/lib/python3.8/dist-packages/schedule/_init_.py", line 172, in _run_job
    ret = job.run()
  File "/usr/local/lib/python3.8/dist-packages/schedule/_init_.py", line 661, in run
    ret = self.job_func()
  File "/BTB-Install-script/Binance1/binance-trade-bot/binance_trade_bot/strategies/multiple_coins_strategy.py", line 35, in scout
    self._jump_to_best_coin(coin, coin_price, excluded_coins)
  File "/BTB-Install-script/Binance1/binance-trade-bot/binance_trade_bot/auto_trader.py", line 179, in _jump_to_best_coin
    self.transaction_through_bridge(best_pair, coin_price, prices[best_pair.to_coin_id])
  File "/BTB-Install-script/Binance1/binance-trade-bot/binance_trade_bot/auto_trader.py", line 50, in transaction_through_bridge
    self.update_trade_threshold(pair.to_coin, price)
  File "/BTB-Install-script/Binance1/binance-trade-bot/binance_trade_bot/auto_trader.py", line 80, in update_trade_threshold
    min_notional = self.manager.get_min_notional(pair.from_coin.symbol, self.config.BRIDGE.symbol)
  File "/usr/local/lib/python3.8/dist-packages/cachetools/decorators.py", line 26, in wrapper
    v = func(*args, **kwargs)
  File "/BTB-Install-script/Binance1/binance-trade-bot/binance_trade_bot/binance_api_manager.py", line 323, in get_min_notional
    return float(self.get_symbol_filter(origin_symbol, target_symbol, "MIN_NOTIONAL")["minNotional"])
  File "/BTB-Install-script/Binance1/binance-trade-bot/binance_trade_bot/binance_api_manager.py", line 310, in get_symbol_filter
    for _filter in self.binance_client.get_symbol_info(origin_symbol + target_symbol)["filters"]
  File "/usr/local/lib/python3.8/dist-packages/binance/client.py", line 502, in get_symbol_info
    res = self.get_exchange_info()
  File "/usr/local/lib/python3.8/dist-packages/binance/client.py", line 459, in get_exchange_info
    return self._get('exchangeInfo', version=self.PRIVATE_API_VERSION)
  File "/usr/local/lib/python3.8/dist-packages/binance/client.py", line 371, in _get
    return self._request_api('get', path, signed, version, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/binance/client.py", line 334, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/binance/client.py", line 315, in _request
    return self._handle_response(self.response)
  File "/usr/local/lib/python3.8/dist-packages/binance/client.py", line 324, in _handle_response
    raise BinanceAPIException(response, response.status_code, response.text)
binance.exceptions.BinanceAPIException: APIError(code=-1003): Too much request weight used; current limit is 1200 request weight per 1 MINUTE. Please use the websocket for live updates to avoid polling the API.

**Comment by Ar4g0rn** [comment]
I forgot to mention that the bot is running but keep throw this error once a while...

**Comment by tntwist** [comment]
How many coins do you have in your list?

**Comment by Ar4g0rn** [comment]
At the time this happened I had 38 coins on the list.
I noticed that my coins list causes the bot to get into stress and it did not stop jumping between coins without taking profit at all so I back to your list And since then the error has not returned.

**Comment by krsh-off** [comment]
Seeing the same issue with 11 coins in the list. Increased scout_sleep_time to 10, the error seems to be gone.
